# Generated by Django 6.0.3 on 2026-04-03 17:36

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('total_cases', models.PositiveIntegerField(default=0)),
                ('cases_by_status', models.JSONField(blank=True, default=dict)),
                ('avg_turnaround_hours', models.FloatField(default=0)),
                ('ai_agreement_rate', models.FloatField(default=0)),
                ('referral_rate', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-period_start'],
            },
        ),
    ]
