# Generated by Django 6.0.3 on 2026-04-03 17:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analytics', '0001_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='analyticssnapshot',
            name='org',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.organization'),
        ),
        migrations.AlterUniqueTogether(
            name='analyticssnapshot',
            unique_together={('org', 'period_start', 'period_end')},
        ),
    ]
