# Generated by Django 6.0.3 on 2026-04-03 17:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cases', '0001_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicalReview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('review_round', models.IntegerField(default=1)),
                ('is_override', models.BooleanField(default=False)),
                ('ai_outcome_before', models.CharField(blank=True, default='', max_length=120)),
                ('confirmed_outcome', models.CharField(max_length=120)),
                ('confidence_before', models.FloatField(blank=True, null=True)),
                ('reason_code', models.CharField(blank=True, default='', max_length=60)),
                ('reviewer_notes', models.TextField(blank=True, default='')),
                ('signed_off_at', models.DateTimeField(blank=True, null=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clinical_reviews', to='cases.case')),
                ('protocol_applied', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews_applied', to='tenants.protocol')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-signed_off_at'],
            },
        ),
    ]
