# Generated by Django 6.0.3 on 2026-04-03 17:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('patient_external_id', models.CharField(blank=True, default='', max_length=120)),
                ('encounter_date', models.DateField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('inference_running', 'Inference Running'), ('inference_complete', 'Inference Complete'), ('needs_review', 'Needs Review'), ('confirmed', 'Confirmed'), ('referral_created', 'Referral Created'), ('followup_scheduled', 'Follow-Up Scheduled'), ('closed', 'Closed')], default='draft', max_length=24)),
                ('notes', models.TextField(blank=True, default='')),
                ('is_urgent', models.BooleanField(default=False)),
                ('clinician', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cases_as_clinician', to=settings.AUTH_USER_MODEL)),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cases', to='tenants.device')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.organization')),
                ('protocol', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cases', to='tenants.protocol')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cases', to='tenants.site')),
                ('technician', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cases_as_technician', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CaseAttachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='cases/attachments/')),
                ('filename', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='cases.case')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_attachments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CaseComment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('body', models.TextField()),
                ('is_internal', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='case_comments', to=settings.AUTH_USER_MODEL)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='cases.case')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CaseImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('eye_side', models.CharField(choices=[('OD', 'OD — Right'), ('OS', 'OS — Left')], max_length=2)),
                ('image_original', models.FileField(upload_to='cases/images/originals/')),
                ('image_thumbnail', models.FileField(blank=True, default='', upload_to='cases/images/thumbnails/')),
                ('quality_score', models.FloatField(blank=True, null=True)),
                ('quality_gate', models.CharField(blank=True, choices=[('gradable', 'Gradable'), ('borderline', 'Borderline'), ('ungradable', 'Ungradable')], default='', max_length=12)),
                ('ungradable_reason', models.CharField(blank=True, default='', max_length=120)),
                ('checksum', models.CharField(blank=True, default='', max_length=64)),
                ('upload_timestamp', models.DateTimeField(auto_now_add=True)),
                ('sequence_order', models.IntegerField(default=1)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='cases.case')),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='captured_images', to='tenants.device')),
                ('uploader', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_images', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['case', 'sequence_order'],
            },
        ),
        migrations.CreateModel(
            name='CaseTimeline',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(max_length=60)),
                ('description', models.TextField(blank=True, default='')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='timeline_events', to=settings.AUTH_USER_MODEL)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline', to='cases.case')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
