# Generated by Django 6.0.3 on 2026-04-03 17:36

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(max_length=60)),
                ('channel', models.CharField(max_length=8)),
                ('recipient_email', models.EmailField(blank=True, default='', max_length=254)),
                ('recipient_phone', models.CharField(blank=True, default='', max_length=30)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('sent', 'Sent'), ('failed', 'Failed'), ('delivered', 'Delivered')], default='queued', max_length=12)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('delivery_status', models.CharField(blank=True, default='', max_length=60)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_logs', to='tenants.organization')),
            ],
            options={
                'ordering': ['-sent_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(max_length=60)),
                ('channel', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS')], max_length=8)),
                ('subject', models.CharField(blank=True, default='', max_length=255)),
                ('body_template', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.organization')),
            ],
            options={
                'ordering': ['event_type'],
                'unique_together': {('org', 'event_type', 'channel')},
            },
        ),
    ]
