# Generated by Django 6.0.3 on 2026-04-03 17:36

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cases', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InferenceJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('complete', 'Complete'), ('failed', 'Failed')], default='pending', max_length=12)),
                ('celery_task_id', models.CharField(blank=True, default='', max_length=255)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.FloatField(blank=True, null=True)),
                ('error_reason', models.TextField(blank=True, default='')),
                ('retry_count', models.IntegerField(default=0)),
                ('model_version', models.CharField(default='v1.0', max_length=60)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inference_jobs', to='cases.case')),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='InferenceResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('eye_side', models.CharField(choices=[('OD', 'OD — Right'), ('OS', 'OS — Left')], max_length=2)),
                ('outcome_label', models.CharField(max_length=120)),
                ('severity', models.CharField(blank=True, default='', max_length=60)),
                ('confidence', models.FloatField()),
                ('raw_output', models.JSONField(blank=True, default=dict)),
                ('heatmap_url', models.URLField(blank=True, default='')),
                ('model_version', models.CharField(default='v1.0', max_length=60)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('case_image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inference_results', to='cases.caseimage')),
                ('job', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='inference.inferencejob')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
