# Generated by Django 6.0.3 on 2026-04-03 17:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inference', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inferenceresult',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='inference.inferencejob'),
        ),
    ]
