# Generated by Django 6.0.3 on 2026-04-03 17:36

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('max_users', models.IntegerField()),
                ('max_storage_gb', models.IntegerField()),
                ('max_cases_per_month', models.IntegerField()),
                ('enabled_modules', models.JSONField(blank=True, default=list)),
                ('price_monthly', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='UsageRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('cases_processed', models.IntegerField(default=0)),
                ('storage_used_gb', models.FloatField(default=0)),
                ('active_users', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-period_start'],
            },
        ),
    ]
