# Generated by Django 6.0.3 on 2026-04-03 17:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('billing', '0001_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usagerecord',
            name='org',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_records', to='tenants.organization'),
        ),
        migrations.AlterUniqueTogether(
            name='usagerecord',
            unique_together={('org', 'period_start')},
        ),
    ]
